# Generated by Django 5.2.13 on 2026-08-12 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=20)),
                ('porte', models.CharField(max_length=20)),
                ('cor_pelagem', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('castracao', models.BooleanField()),
                ('descricao_temperamento', models.TextField()),
                ('data_entrada', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'animal',
                'verbose_name_plural': 'animais',
                'db_table': 'animal',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='FotoAnimal',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('url_foto', models.URLField(max_length=500)),
                ('animal', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='animais.animal')),
            ],
            options={
                'verbose_name': 'foto do animal',
                'verbose_name_plural': 'fotos dos animais',
                'db_table': 'foto_animal',
            },
        ),
    ]
