# Generated by Django 5.2.13 on 2026-08-12 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animais', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id_vacina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_vacina', models.CharField(max_length=100)),
                ('especie_alvo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'vacina',
                'verbose_name_plural': 'vacinas',
                'db_table': 'vacina',
                'ordering': ('nome_vacina',),
            },
        ),
        migrations.CreateModel(
            name='CondicaoSaude',
            fields=[
                ('id_condicao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_condicao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_diagnostico', models.DateField()),
                ('gravidade', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(db_column='id_adm', limit_choices_to={'perfil': 'ADMINISTRADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='condicoes_saude_registradas', to='usuarios.usuario')),
                ('animal', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.CASCADE, related_name='condicoes_saude', to='animais.animal')),
            ],
            options={
                'verbose_name': 'condição de saúde',
                'verbose_name_plural': 'condições de saúde',
                'db_table': 'condicao_saude',
                'ordering': ('-data_diagnostico',),
            },
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id_vacinacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_aplicacao', models.DateField()),
                ('data_proxima_dose', models.DateField()),
                ('dose', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=100)),
                ('administrador', models.ForeignKey(db_column='id_adm', limit_choices_to={'perfil': 'ADMINISTRADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='vacinacoes_registradas', to='usuarios.usuario')),
                ('animal', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='animais.animal')),
                ('vacina', models.ForeignKey(db_column='id_vacina', on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes', to='saude.vacina')),
            ],
            options={
                'verbose_name': 'vacinação',
                'verbose_name_plural': 'vacinações',
                'db_table': 'vacinacao',
                'ordering': ('-data_aplicacao',),
            },
        ),
    ]
