# Generated by Django 5.2.13 on 2026-08-12 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0001_initial'),
        ('animais', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAdocao',
            fields=[
                ('id_solicitacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_AVALIACAO', 'Em avaliação'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=12)),
                ('administrador_avaliador', models.ForeignKey(blank=True, db_column='id_adm_avaliador', limit_choices_to={'perfil': 'ADMINISTRADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_avaliadas', to='usuarios.usuario')),
                ('animal', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_adocao', to='animais.animal')),
                ('cliente', models.ForeignKey(db_column='id_cliente', limit_choices_to={'perfil': 'CLIENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_adocao', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'solicitação de adoção',
                'verbose_name_plural': 'solicitações de adoção',
                'db_table': 'solicitacao_adocao',
                'ordering': ('-data_solicitacao',),
            },
        ),
    ]
