# Generated by Django 5.2.13 on 2026-08-12 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0002_solicitacaoadocao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
